sudo: false

os:
  - linux
  - osx

language: d

d:
  - ldc-1.1.0
  - dmd

env:
  - ARCH="x86_64"

install:
  - wget -q -O - "http://bit.ly/Doveralls" | bash
  - chmod +x doveralls

script:
  - dub test -b unittest-cov
  - ./doveralls
