sudo: false

os:
  - linux
  - osx

language: d

d:
  - ldc-1.1.0
  - dmd

matrix:
  include:
    - d: ldc-1.1.0
  allow_failues:
    - d: ldc-1.1.0

env:
  - ARCH="x86_64"

install:
  - dub fetch doveralls

script:
  - dub test -b unittest-cov
  - dub run doveralls
